server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testDB?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1111}
    hikari:
      poolName: Hikari
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      default_batch_fetch_size: 20
      query:
        in_clause_parameter_padding: true

    show-sql: false # true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
        #integrator_provider: com.example.demo.provider.DemoClassImportIntegratorProvider
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 30
    open-in-view: false

db:
  data-source-settings:
    - type: MASTER
      url: jdbc:mysql://127.0.0.1:3306/testDB?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USERNAME:admin}
      password: ${DB_PASSWORD:1111}
      hikari:
        poolName: Hikari
        maximum-pool-size: 5
        minimum-idle: 2
    - type: REPLICA
      url: jdbc:mysql://127.0.0.1:3306/testDB?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USERNAME:admin}
      password: ${DB_PASSWORD:1111}
      hikari:
        poolName: Hikari
        maximum-pool-size: 5
        minimum-idle: 2

decorator:
  datasource:
    exclude-beans: lazyConnectionDataSourceProxy
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j

logging:
  level:
    root: info
    org:
      hibernate:
        SQL_SLOW: info
        SQL: info # DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: info # TRACE
